### ISSUE TITLE
Not working with shared module

### ISSUE THREAD

**Issue by HugoHeneault** [zyra/ionic-tooltips#14]
I'm using your tooltip module on a lazy loaded project. 

I have a shared module that I import in my lazy-loaded page si I don't have to import `TooltipsModule`,  `TranslateModule` and more on every page... But it's not working. 

When I use `TooltipsModule` straight in my page module, it's working. 

Any ideas? Thanks!

**Comment by cvandyke1217** [comment]
I second this issue.

**Comment by mebibou** [comment]
did you try to add the module in the `exports` array where you import it?

**Comment by mebibou** [comment]
@tangjon yep that is how you should share modules in Angular
