### ISSUE TITLE
Use HTML in tooltips

### ISSUE THREAD

**Issue by HugoHeneault** [zyra/ionic-tooltips#15]
I would like to add some markup (at least some `<br />`), but HTML is escaped. Any ideas on how I could achieve that? 

Thanks!

**Comment by yanglongji** [comment]
have you resolved that?

**Comment by HugoHeneault** [comment]
Unfortunately, nope :(

**Comment by telran** [comment]
Fork the project and change following in BoxComponent:
From: template: '{{ text }}',
To: tempalte: '<div [innerHtml]="text">'

**Comment by darron1217** [comment]
This project seeemed not maintaining, so I created forked project which supports HTML content

https://github.com/darron1217/ionic-tooltips
`npm i --save ionic-tooltips-html`

**Comment by himalayaahuja** [comment]
can you show some demo if it works? showing html content in tooltip?
