### ISSUE TITLE
Tooltip does not disappear when clicking on the element containing the "hover" event for display

### ISSUE THREAD

**Issue by aprillahey** [zyra/ionic-tooltips#17]
I have the tooltip placed on various button elements using the hover event. They are displayed correctly and if I mouse-out they disappear. But if I click on that button, the tooltip does NOT disappear. Is this a known issue? Is there a solution? Help? Do I need to manually destroy the tooltip in my click event?

HTML Example:
<ion-toolbar>
<ion-buttons>
<button id="buttonID" tooltip="Some Text" navTooltip arrow event="hover" ion-button icon-only (click)="someEvent()">
            <ion-icon name="arrow-back"></ion-icon>
        </button>
</ion-buttons>
</ion-toolbar>

I do have everything in my app.module that is needed.

Example:
import { TooltipsModule } from 'ionic-tooltips';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  imports: [
     TooltipsModule,
     BrowserAnimationsModule
],

**Comment by benjcallaghan** [comment]
I have the same issue. I've tried setting active=false during my click handlers, but that creates new errors similar to Issue #20.

**Comment by madoBaker** [comment]
I've tried to replicate bug but wasn't able to...
Could it be that your `(click)` function was changing the page?
That's an older issue that would cause the tooltip to stay visible if user changes page. Should be fixed with latest release
