### ISSUE TITLE
specify the arrow's position

### ISSUE THREAD

**Issue by yanglongji** [zyra/ionic-tooltips#18]
if it can specify the arrow's position according to the position where user clicks rather than always left:10px, it'd be better

**Comment by yanglongji** [comment]
or we can defined the position on attribute

**Comment by benjcallaghan** [comment]
I would also like the ability to customize the position of the arrow. In many of my tooltips, the arrow doesn't even point to the button. The buttons are really small, so the arrows are off to the right of the button.
