### ISSUE TITLE
show only one tooltip at a time 

### ISSUE THREAD

**Issue by ajayadglobal360** [zyra/ionic-tooltips#21]
how to disable other tooltip when i click or press on other tag or buton

**Comment by ihadeed** [comment]
It's not possible at the moment, but it will be possible in the future releases.

**Comment by ajayadglobal360** [comment]
How many days we have to wait for this ?

On Nov 11, 2017 3:33 AM, "Ibby Hadeed" <notifications@github.com> wrote:

It's not possible at the moment, but it will be possible in the future
releases.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zyra/ionic-tooltips/issues/21#issuecomment-343599303>,
or mute the thread

**Comment by ihadeed** [comment]
Probably by the end of this year :)

**Comment by jcyh0120** [comment]
Need this feature, too. This is the best plugin I can find for giving user a good tour guide experience.
