### ISSUE TITLE
need to hide when pushes to another page

### ISSUE THREAD

**Issue by yanglongji** [zyra/ionic-tooltips#23]
as title

**Comment by PilarMassL** [comment]
What whas de solution ?

**Comment by Lukizzle** [comment]
I have a (hacky) workaround for this. When pushing to a new page, call function "hideTooltips()". Then define function:
hideTooltips() { let elements = document.getElementsByTagName("tooltip-box"); for(var i =0, il = elements.length;i<il;i++){ elements[i].className += " hidden"; } }
And in your css, add:
tooltip-box.hidden { display: none !important; }
