### ISSUE TITLE
How can i show tooltip without clicking a button ? i want it to be there once page is opened

### ISSUE THREAD

**Issue by jessicastorm1986** [zyra/ionic-tooltips#25]
Hii,

I have installed and implemented this on a button but what i want is the tooltip to be there once the page is opened, just for instructions. How do i do this ?

**Comment by ihadeed** [comment]
That's not possible at the moment, but it's on the roadmap.

**Comment by willyboy** [comment]
@ihadeed @jessicastorm1986 Just set "active" to true.

**Comment by jcyh0120** [comment]
i set active to true and it immediately show then closed.

**Comment by ihadeed** [comment]
@jcyh0120 change the duration with the `[duration]` attribute
