### ISSUE TITLE
Tooltip doesn't go away after view is changed

### ISSUE THREAD

**Issue by madoBaker** [zyra/ionic-tooltips#34]
If you're hovering over an element with a tooltip attached to it and view is changed before moving away from element, attached tooltip won't ever go away until app is refreshed

**Comment by Chumillas** [comment]
It happens to me too without hovering

**Comment by Chumillas** [comment]
@richie50 
Add active directive to the tooltip with `[active]="myTooltip " ` and display it setting myTooltip to true `this.myTooltip=true`

And then when user leaves the view hide it
```
ionViewWillLeave() {
    this.myTooltip = false;
}
```

**Comment by madoBaker** [comment]
Should be fixed in latest release.
