### ISSUE TITLE
Lazy Load Browser Module

### ISSUE THREAD

**Issue by ajonp** [zyra/ionic-tooltips#4]
Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. at new BrowserModule (http://localhost:8100/build/main.js:48813:19) at BeerPageModuleInjector.createInternal (ng:///BeerPageModule/module.ngfactory.js:195:28) at BeerPageModuleInjector.NgModuleInjector.create (http://localhost:8100/build/main.js:3919:76) at NgModuleFactory.create (http://localhost:8100/build/main.js:3892:18) at http://localhost:8100/build/main.js:84454:53 at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/main.js:4510:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911) at r.run (http://localhost:8100/build/polyfills.js:3:4140) at http://localhost:8100/build/polyfills.js:3:13731 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655) at Object.onInvokeTask (http://localhost:8100/build/main.js:4501:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9576) at r.runTask (http://localhost:8100/build/polyfills.js:3:4831) at o (http://localhost:8100/build/polyfills.js:3:1891) at <anonymous>

**Comment by thanhvc** [comment]
I got the the same this exception  when integrate the ionic-tooltips. 
Would you have any the solution for this? 

the dependencies are using:
"@angular/animations": "4.1.3",
 "@angular/common": "4.1.3",
"ionic-tooltips": "^1.0.0",

**Comment by ThomasKientz** [comment]
Same for me as the `BrowserAnimationsModule` was already imported in `app.module.ts`.

You can edit the mode `/node_modules/ionic-tooltips/dist/tooltips.module.js` and comment the line 23 to solve this :

```
imports: [
  IonicModule,
  // BrowserAnimationsModule
],
```
then restart `ionic serve`

**Comment by ajonp** [comment]
@ThomasKientz unfortunately when you push to a build server you can't open up node_modules :(

**Comment by YamanSehzade** [comment]
Hi @ThomasKientz . Could you help me please ?
i have a similar problem.
i edit the mode /node_modules/ionic-tooltips/dist/tooltips.module.js and comment the line 23 
`ionic serve` works great but
`ionic cordova run android --prod ` throwing an error

**_i have this configurations:_**

### _app.module.ts:_
> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
> import { Facebook } from '@ionic-native/facebook';
> import { GooglePlus } from '@ionic-native/google-plus';
> import { Camera } from '@ionic-native/camera';
> import { SuperTabsModule } from 'ionic2-super-tabs';
> import { PROVIDERS } from './../providers/index';
> import { BrowserModule } from '@angular/platform-browser';
> import { ErrorHandler, NgModule } from '@angular/core';
> import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
> import { SplashScreen } from '@ionic-native/splash-screen';
> import { StatusBar } from '@ionic-native/status-bar';
> import { HttpModule } from "@angular/http";
> import { AngularFireModule } from 'angularfire2';
> import { AngularFireAuthModule } from 'angularfire2/auth';
> import { AngularFireDatabaseModule } from 'angularfire2/database';
> 
> import { MyApp } from './app.component';
> 
> export const firebaseConfig = {};
> 
> @NgModule({
>   declarations: [
>     MyApp,
>   ],
>   imports: [
>     BrowserAnimationsModule,
>     BrowserModule,
>     HttpModule,
>     IonicModule.forRoot(MyApp),
>     SuperTabsModule.forRoot(),
>     AngularFireModule.initializeApp(firebaseConfig),
>     AngularFireAuthModule,
>     AngularFireDatabaseModule,
>   ],
>   bootstrap: [IonicApp],
>   entryComponents: [
>     MyApp,
>   ],
>   providers: [
>     ...PROVIDERS,
>     StatusBar,
>     SplashScreen,
>     { provide: ErrorHandler, useClass: IonicErrorHandler },
>     Camera,
>     Facebook,
>     GooglePlus,
>   ]
> })
> export class AppModule { }

### _lazy page module :_

> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
> import { TooltipsModule } from 'ionic-tooltips';
> import { DictionaryEditPage } from './dictionary-edit';
> import { NgModule } from '@angular/core';
> import { IonicPageModule } from 'ionic-angular';
> import { PipesModule } from "../../pipes/pipes.module";
> 
> @NgModule({
>   declarations: [
>     DictionaryEditPage,
>   ],
>   imports: [
>     IonicPageModule.forChild(DictionaryEditPage),
>     PipesModule,
>     TooltipsModule,
>   ],
>   exports: [
>     DictionaryEditPage
>   ]
> })
> export class DictionaryEditPageModule { }

### throw this error:

> BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by ihadeed** [comment]
Should be fixed now. Install the latest version and import BrowserAnimationsModule manually to your app's root module.

**Comment by YamanSehzade** [comment]
it works. thank you..
