### ISSUE TITLE
Only for buttons ???

### ISSUE THREAD

**Issue by LucaGabi** [zyra/ionic-tooltips#40]
Hi,

Is this working on buttons?

I would use it to show errors in input forms ..

**Comment by richie50** [comment]
seems like it :(

**Comment by LucaGabi** [comment]
I managed to also use it for other things like inputs in ionic in the end but when I the keyboard shows up they change position as well so not useful with that problem... I'll come back with details if interested

**Comment by maugrejanin** [comment]
I used the below workaround to use it on ion-input and it work as well

` setTimeout(() => {
        myInputElement._elementRef.nativeElement.click(); 
      }, 100);`
