### ISSUE TITLE
i found following error when using ionic tooltip

### ISSUE THREAD

**Issue by amitdk04** [zyra/ionic-tooltips#6]
ionic-app-script task: "build"
[11:45:38]  Error: ./node_modules/ionic-tooltips/dist/tooltips.module.ts Module not found: Error: Can't resolve
            '@angular/platform-browser/animations' in 'D:\IONIC\reetzy\node_modules\ionic-tooltips\dist' resolve
            '@angular/platform-browser/animations' in 'D:\IONIC\reetzy\node_modules\ionic-tooltips\dist' Parsed request
            is a module using description file: D:\IONIC\reetzy\node_modules\ionic-tooltips\package.json (relative path:
            ./dist) Field 'browser' doesn't contain a valid alias configuration after using description file:
            D:\IONIC\reetzy\node_modules\ionic-tooltips\package.json (relative path: ./dist) resolve as module looking
            for modules in D:\IONIC\reetzy\node_modules using description file: D:\IONIC\reetzy\package.json (relative
            path: ./node_modules) Field 'browser' doesn't contain a valid alias configuration after using description
            file: D:\IONIC\reetzy\package.json (relative path: ./node_modules) using description file:
            D:\IONIC\reetzy\node_modules\@angular\platform-browser\package.json (relative path: ./animations) no
            extension Field 'browser' doesn't contain a valid alias configuration
            D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations doesn't exist .ts Field 'browser' doesn't
            contain a valid alias configuration D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.ts
            doesn't exist .js Field 'browser' doesn't contain a valid alias configuration
            D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.js doesn't exist .json Field 'browser'
            doesn't contain a valid alias configuration
            D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.json doesn't exist as directory
            D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations doesn't exist
            [D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations]
            [D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.ts]
            [D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.js]
            [D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations.json]
            [D:\IONIC\reetzy\node_modules\@angular\platform-browser\animations] @
            ./node_modules/ionic-tooltips/dist/tooltips.module.ts 5:0-79 @ ./node_modules/ionic-tooltips/dist/index.js @
            ./src/app/app.module.ts @ ./src/app/main.ts
Error: ./node_modules/ionic-tooltips/dist/tooltips.module.ts

**Comment by HugoHeneault** [comment]
Did you manage to build for production? 🤔
