### ISSUE TITLE
ERROR "No provider for TooltipController"

### ISSUE THREAD

**Issue by sertal70** [zyra/ionic-tooltips#61]
**Describe the bug**
When the app load a page where a `tooltip` directive is used, the following error happens:
```
Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[Tooltip -> TooltipController]: StaticInjectorError(Platform: core)[Tooltip -> TooltipController]: NullInjectorError: No provider for TooltipController! 
```

I suspect I'm doing something wrong but I cannot identify what it is. Having a look at the example project didn't help me to sort out this.

Thanks for help!

**To Reproduce**
1. install the directive (I'm using v3 because of Ionic v3)
`npm i ionic-tooltips@3 --save`
2. add module to app.module.ts
```javascript
import { TooltipsModule } from 'ionic-tooltips';
...
  imports: [
   ...
    IonicModule.forRoot(MyApp),
    TooltipsModule,
    ...
```
3. add a `tooltip` directive on any html element of the page:
```html
...
<img tooltip='sample text' [event]='hover'/>
...
```

**Expected behavior**
When the app is run and the page is displayed, the text "sample text" is displayed if I move the mouse cursor on the image 

**Desktop (please complete the following information):**
 - OS: macOS 10.12.4
 - Browser Safari
 - Version 12.0,.3
- Angular Version: 5.2.11

**Comment by sertal70** [comment]
***UPDATE***

If I add `TooltipController` to the list of providers in `app.module.ts`, the error goes away:

```javascript
import { TooltipsModule, TooltipController } from 'ionic-tooltips';
...
  imports: [
   ...
    IonicModule.forRoot(MyApp),
    TooltipsModule,
    ...
  ],
  providers: [
   ...
    TooltipController,
   ...
  ]
```

Why is this not present in the example project?

**Comment by ihadeed** [comment]
You need to import it in your `app.module.ts` as `TooltipsModule.forRoot()`

**Comment by sertal70** [comment]
thanks @ihadeed for this, if it is the fix indeed it should be applied to the [example project](https://github.com/zyra/ionic-tooltips-example) too, right?
